### ISSUE TITLE
dies when encountering fifos, sockets etc.

### ISSUE THREAD

**Issue by faxm0dem** [amio/flaming-disk-usage#2]
```
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOTDIR: not a directory, scandir '/var/tmp/syslog-ng.dst.fifo'
```

```
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOTDIR: not a directory, scandir '.config/chromium/SingletonSocket'
    at Error (native)
```

**Comment by amio** [comment]
Got it :)

**Comment by amio** [comment]
This bug has been fixed in [node-directory-tree](https://github.com/mihneadb/node-directory-tree/commit/3e54e4b8b710efbe1c7290a0d8a47bdc5591ac8f#diff-e70467b8a29d8502512eee6e80d799eeR20) but it hasn't published.

I've open an issue(mihneadb/node-directory-tree#15) addressing the new release for it.
